accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('ai_check/', ai_check, name='ai_check'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zeronine.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

join/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('join_create/<int:id>/', join_create, name='join_create'),
    ]

zeronine/urls.py
from django.urls import path, include
from .views import *

app_name = 'zeronine'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('product/', include('product.urls')),
    path('join/', include('join.urls')),
    path('zzim/', include('zzim.urls')),
    path('mypage/', include('mypage.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from zeronine.models import Member

class RegisterForm(UserCreationForm):
    email = forms.EmailField(
        label=('이메일'),
        required=True,
        widget=forms.EmailInput(
                attrs={
                    'class': 'form-control',
                    'required': 'True',
                }
        )
    )
    class Meta:
        model = Member
        fields = ['name', 'username', 'phone', 'email']

        def clean_password2(self):

            cd = self.cleaned_data
            if cd['password1']!=cd['password2']:
                raise forms.ValidationError
            return cd['password2']

accounts/views.py
from django.shortcuts import render
from accounts.forms import RegisterForm
from zeronine.models import *

def register(request):
    current_category = None
    categories = Category.objects.all()
    member = Member.objects.all()

    if request.method == 'POST':
        member_form = RegisterForm(request.POST)
        if member_form.is_valid():
            new_member = member_form.save(commit=False)
            new_member.set_password(member_form.cleaned_data['password2'])
            new_member.save()
            return render(request, 'accounts/register_done.html', {'new_member':new_member,
                                                                   'member':member,
                                                                   'current_category': current_category,
                                                                   'categories': categories})
    else:
        member_form = RegisterForm()


    return render(request, 'accounts/register.html', {'form':member_form})


def ai_check(request):

    return render(request, 'accounts/ai_check.html')

accounts/templates/accounts/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger" style="background: white; border-color: white">
                <img src="/static/img/error.png" style="width:15px; margin-bottom: 3px"><strong style="color: red">&nbsp;&nbsp;{{ field.label }}</strong>
                <h8 style="color: red">&nbsp;{{ error }}</h8>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger" style="background: white; border-color: white">
            <img src="/static/img/error.png" style="width:20px; "><strong style="color: red">&nbsp;{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

accounts/templates/accounts/login.html
<html>
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Questrial&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<style>

@import url('https://fonts.googleapis.com/css2?family=Hahmlet:wght@200;400&family=Noto+Sans+KR&display=swap');

* {
    font-family: 'Noto Sans KR', sans-serif;
}

html, body{
    width:100%;
    overflow-x:hidden;
}

@media screen and (min-width: 1025px) { /* 줄이기 전 */
  .zn_logo {
      width: 170px;
      margin-top: -25px;
      text-align: center;
  }
}

@media screen and (max-width: 1024px) {
  .zn_logo {
      max-width: 150px;
      margin-top: -25px;
      text-align: center;
  }
}

@media screen and (min-width: 1025px) { /* 줄이기 전 */
  .footer {
      width: 100%;
      height: 280px;
      padding: 15px;
      text-align: left;
      background-color: #F2F2F2;
      margin-top: 100px;
  }
}

@media screen and (max-width: 1024px) {
  .footer {
      width: 130%;
      height: 280px;
      padding: 15px;
      text-align: left;
      background-color: #F2F2F2;
      margin-top: 100px;
  }
}

.footer_logo {
    font-family: 'Questrial', sans-serif;
    font-size: 30px;
}


@media screen and (min-width: 1025px) {
  .footer_logo {
      font-size: 50px;
      margin-left: 230px;
      margin-top: 40px;
  }
}

@media screen and (max-width: 1024px) {
  .footer_logo {
      font-size: 32px;
      margin-left: 25px;
      margin-top: 40px;

  }
}

@media screen and (min-width: 1025px) {
  .footer_p {
        font-size: 15px;
        margin-left: 230px;
  }
}

@media screen and (max-width: 1024px) {
  .footer_p {
      font-size: 11px;
       margin-left: 25px;
  }
}

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      border: 0px solid rosybrown;
    }

    body {
      font-family: 'Noto Sans KR', sans-serif;
      font-size: 0.9rem;
      font-weight: 300;
      color: #555;
    }

    button {
      padding: 20px;
      background: none;
      width: 100%;
      margin-bottom: 0.8rem;
      transition: 0.6s;
      cursor:pointer;
    }

  @media screen and (max-width: 1025px) {
  .login {
      padding: 5.5rem 0;
      font-size: 13px;
      max-width: 300px;
      margin: 0 auto;
      text-align: center;
  }
}

    .login {
      padding: 5.5rem 0;
      width: 450px;
      margin: 0 auto;
      text-align: center;
    }

    .login input {
      width: 100%;
      padding: 20px;
      background: none;
      border:1px solid #999;
      margin-bottom: 0.5rem;
    }

    .login input[type="checkbox"] {
      width: 15px;
    }

    .login>:nth-child(3)>div {
      display: flex;
      justify-content: space-between;
      margin-bottom: 2.5rem;
    }

    .login a {
      color: #555;
      text-decoration: none;
    }

    .login>:nth-child(3)>:nth-child(5) {
      background:#849160;
      color: white;
      font-size: 16px;
    }

    .login>:nth-child(3)>:nth-child(5):hover {
      background: black;
    }

    .login>:nth-child(3)>:last-child {
      background: white;
      border: 1px solid #444;
      transition: 0.6s;
    }

    .login>:nth-child(3)>:last-child:hover {
      border: 1px solid #C80A1E;
      color: #C80A1E;
    }

    .login>:nth-child(4) {
      display: flex;
      justify-content: space-between;
      text-align: center;
      padding:1.3rem 0;
    }

    .login>:nth-child(4) div {
      width: 45%;
      height: 1px;
      background: #999;
      line-height: 2rem;
      margin-top: 0.7rem;
    }

    .login>:nth-child(4) p {
      margin: 0;
    }

    .login>:nth-child(5)>div{
      display: flex;
      padding:0 5.5rem;
    }

    .login>:nth-child(5)>div div{
      width:70px;
      height:70px;
      border-radius: 50%;
      border:1px solid #999;
      text-align:center;
      margin:0 0.7rem;
      line-height: 5.8rem;
      cursor:pointer;
    }

    .login>:nth-child(5)>div img{
      width:30px;
      height:30px;
      margin-top: 20px;
      opacity:0.45;
    }

    .login>:nth-child(5)>div img:hover{
      opacity:0.6;
    }

</style>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
     {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">

<div class="container my-3" style="text-align: center; margin: 0 auto;">
        <div class="navbar navbar-expand-md navbar-light" style="text-align: center; margin: 0 auto;">
        <a class="navbar-brand" href="/" style="text-align: center; text-decoration: none;"><img class="zn_logo" src="/static/img/zeronine_logo_image.png"></a>
    </div>

    <div class="row">
        <div class="col-12">
            <hr width="100%" style="margin-top:-5px; text-align: center">
            <br>
        </div>
    </div>

    <form method="post" class="post-form" action="{% url 'zeronine:login' %}">
        {% csrf_token %}
        {% include "accounts/form_errors.html" %}

  <article class="login" style="margin-top: -40px; text-align: center; justify-content: center;">
    <h2><b>로그인</b></h2>
    <p>가입하신 제로나인 아이디와 비밀번호를 입력해주세요.</p>

    <section>
      <input type="text" placeholder="아이디" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}"><br>
      <input type="password" placeholder="비밀번호" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">

      <div>
        <div>
        </div>
           <a href="{% url 'zeronine:ai_check' %}"><p>제로나인이 처음이신가요? <b style="color: #637B46">회원가입</b></p></a>
      </div>

      <button type="submit">로그인</button><br>

    </section>
  </article>
    </form>
</div>
     <footer class="footer" style="text-align: left; ">
         <p class="footer_logo" style="margin-bottom: -1px;">ZERONINE</p>
         <p class="footer_p" >ZERONINE ⓒ 2021 ALL RIGHTS RESERVED.</p>
         <p class="footer_p" style="color: #6E6E6E;">제로나인 | 주소: 서울특별시 성동구 살곶이길 200 한양여자대학교 <br>
             메일: zeronineproject2021@gmail.com | CALL: 010-6352-4046</p>
     </footer>
</div>
</body>

</html>

accounts/templates/accounts/register.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>

@import url('https://fonts.googleapis.com/css2?family=Hahmlet:wght@200;400&family=Noto+Sans+KR&display=swap');

* {
    font-family: 'Noto Sans KR', sans-serif;
}

html, body{
    width:100%;
    overflow-x:hidden;
}

body {
      font-family: 'Noto Sans KR', sans-serif;
      font-size: 0.9rem;
      font-weight: 300;
      color: #555;
    }

* {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      border: 0px solid rosybrown;
}

.footer_logo {
    font-family: 'Questrial', sans-serif;
    font-size: 50px;
}

@media screen and (min-width: 1025px) {
  .footer {
      width: 100%;
      height: 280px;
      padding: 15px;
      text-align: left;
      background-color: #F2F2F2;
      margin-top: 100px;"
  }
}

@media screen and (max-width: 1024px) {
  .footer {
      width: 133%;
      height: 280px;
      padding: 15px;
      text-align: left;
      background-color: #F2F2F2;
      margin-top: 100px;"
  }
}


@media screen and (min-width: 1025px) {
  .footer_logo {
        font-size: 50px;
        margin-left: 230px;
  }
}

@media screen and (max-width: 1024px) {
  .footer_logo {
      font-size: 30px;
      margin-left: 25px;
  }
}

@media screen and (min-width: 1025px) {
  .footer_p {
        font-size: 15px;
        margin-left: 230px;
  }
}

@media screen and (max-width: 1024px) {
  .footer_p {
      font-size: 11px;
       margin-left: 25px;
  }
}

button {
  font-size: 0.7rem;
  text-transform: uppercase;
  padding: 10px 30px;
  border: 1px solid #ccc;
  background: white;
  transition: 0.7s;
}

button:hover {
  background: black;
  color: white;
  cursor: pointer;
  transition: 0.7s;
}

input::placeholder {
  color: #777;
}

hr{
  border: 0.5px solid rgba(0, 0, 0, 0.1);
}

.bbb button {
  margin: 0px;
  padding: 10px;
  background: #849160;
  border-color: white;
  color: #fff;
  margin-top: 5px;
  height: 60px;
  width: 450px
  }

  .bbb button:hover {
    background: black;
    border: 1px solid white;
    color: white;
    }

@media screen and (max-width: 1025px) {
  .registerbtn {
      padding: 50px 0;
      margin: 0 auto;
      text-align: center;
      max-width: 330px;
  }
}

@media screen and (max-width: 1025px) {
  .join {
      padding: 50px 0;
      margin: 0 auto;
      text-align: center;
      max-width: 330px;
  }
}

@media screen and (max-width: 1025px) {
  .register {
      font-size: 10px;
  }
}

  .join {
      padding: 5rem 0 6.5rem 0;
      width: 450px;
      margin: 0 auto;
      text-align: center;
  }


.join h3 {
  text-align: center;

}

.join input {
  margin: 0 auto;
  border: 1px solid #ccc;
  color: #4f6185;
  margin-bottom: 10px;
  height: 51px;
  width: 100%;
}

@media screen and (min-width: 1025px) {
  .zn_logo {
      width: 170px;
      margin-top: -60px;
      margin-bottom: 15px;
  }
}

@media screen and (max-width: 1024px) {
  .zn_logo {
      width: 170px;
      margin-top: -60px;
      margin-bottom: 15px;
  }
}

@media screen and (min-width: 1025px) {
  .register-form {

  }
}

@media screen and (max-width: 1024px) {
  .register-form {

  }
}

</style>

<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Questrial&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
     {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">

    <article class="join">
    <nav class="navbar navbar-expand-sm navbar-light flex-column align-items-stretch">
        <div class="navbar navbar-expand-md navbar-light" style="text-align: center">
        <a class="navbar-brand" href="/" style="text-align: center; text-decoration: none;"><img class="zn_logo" src="/static/img/zeronine_logo_image.png"></a>
        </div>
    </nav>
        <hr width="90%" style="margin-top:-30px; margin-left:28px; text-align: center">
        <br>

        <p style="margin-top: -30px;">{% include "accounts/form_errors.html" %}</p>

        <h2 style="justify-content: center; text-align: center; margin-top: 40px; margin-bottom: 50px;"><b>회원가입</b><br>
        <p class="register" style="font-size: 15px; margin-top: 20px; margin-bottom: -20px;">제로나인 회원가입을 환영합니다.<br>회원으로 가입하시면 다양한 혜택과 서비스를 이용하실 수 있습니다.</p></h2>

         <form method="post" class="register-form">
        {% csrf_token %}
        <div>
        <input type="text" class="form-control" name="name" id="name" value="{{ form.name.value|default_if_none:'' }}" placeholder="이름을 입력하세요">
      </div>

      <div>
        <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}" placeholder="아이디 (4~12자 영문 대,소문자)">
      </div>

      <div>
        <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}" placeholder="비밀번호">
      </div>

      <div>
        <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}" placeholder="비밀번호 확인">
      </div>

      <div>
        <input type="text" class="form-control" name="phone" id="phone" value="{{ form.phone.value|default_if_none:'' }}" placeholder="전화번호를 입력하세요.">
      </div>

      <div>
       <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}" placeholder="이메일을 입력하세요.">
      </div>
             <div class="bbb" style="text-align: center">
              <button class="registerbtn" type="submit">가입하기</button><br>
             </div>

             <div style="text-align: center; margin-top: 15px;">
              <span class="col-8 text-right">이미 계정이 있으신가요? <a href="{% url 'zeronine:login' %}", style="color: #637B46; text-decoration: none;"><b>로그인</b></a></span>
             </div>
   </form>

</article>

     <footer class="footer" style="text-align: left; background-color: #F2F2F2;">
         <p class="footer_logo" style="margin-top: 40px;">ZERONINE</p>
         <p class="footer_p">ZERONINE ⓒ 2021 ALL RIGHTS RESERVED.</p>
         <p class="footer_p" style="color: #6E6E6E;">제로나인 | 주소: 서울특별시 성동구 살곶이길 200 한양여자대학교 <br>
             메일: zeronineproject2021@gmail.com | CALL: 010-6352-4046</p>
     </footer>
</div>
</div>
</body>
</html>

accounts/templates/accounts/register_done.html
{% extends 'base.html' %}
{% block title %} 회원가입 완료 {% endblock %}
{% block content %}
<script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>
  html, body{
    width:100%;
    overflow-x:hidden;
}

    button {
      font-size: 0.7rem;
      text-transform: uppercase;
      padding: 10px 30px;
      border: 1px solid #ccc;
      background: white;
      transition: 0.3s;
      max-width: 100px;
    }

    button:hover {
      background: crimson;
      color: white;
      cursor: pointer;
    }

/* 회원가입을 환영합니다 문구 */
    .wel1{
      width: 500px;
      margin: 0 auto;
      text-align: center;
      font-size: 1.3rem;
      margin-bottom: 32px;
      color:darkgrey;
    }

@media screen and (max-width: 1024px) {
  .wel1 {
      font-size: 15px;
      margin-right: 330px;
  }
}

 ion-icon {
      font-size: 5rem;
      margin: 2.4rem auto;
      margin-bottom: 10px;
      color: #c80a1e;
    }

@media screen and (max-width: 1024px) {
  ion-icon {
      font-size: 60px;
      margin-right: 130px;
  }
}

/* 회원가입이 완료되었습니다 문구 */
    .wel1 h1{
      font-size: 2.5rem;
      margin-bottom: 30px;
      color: #333;
    }

@media screen and (max-width: 1024px) {
  .wel1 h1 {
      font-size: 23px;
      margin-right: 130px;
  }
}

@media screen and (max-width: 1024px) {
  .wel1 h3 {
      font-size: 17px;
      margin-right: 130px;
      margin-top: -10px;
  }
}

/* 홈으로, 로그인 */
    .wel2{
      width: 500px;
      margin: 0 auto;
      padding:2rem 0;
      text-align: center;
    }

    .wel2 a{
      width: 200px;
      padding: 10px 80px;
      margin: auto 10px;
      border: 1px solid #000;
      font-size: 1rem;
      color: #000;
      transition: .5s;
    }

    .wel2 a:hover{
      background: #000;
      color: #fff;
    }

@media screen and (min-width: 1025px) {
    .well {
        display: none;
    }
}

@media screen and (min-width: 1025px) {
    .well2 {
        display: none;
    }
}

@media screen and (max-width: 1024px) {
    .wel2{
      width: 500px;
      margin: 0 auto;
      padding:2rem 0;
      text-align: center;
    }
}

@media screen and (max-width: 1024px) {
    .wel2 a{
      width: 200px;
      padding: 10px 80px;
      margin: auto 10px;
      border: 1px solid #000;
      font-size: 1rem;
      color: #000;
      transition: .5s;
    }
}


@media screen and (max-width: 1024px) {
    .wel2 {
        display: none;
    }
}

@media screen and (max-width: 1024px) {
    .well{
      width: 500px;
      margin-left: -65px;
      padding:2rem 0;
      text-align: center;
    }
}

@media screen and (max-width: 1024px) {
    .well a{
      width: 200px;
      padding: 10px 80px;
      margin: auto 10px;
      border: 1px solid #000;
      font-size: 1rem;
      color: #000;
      transition: .5s;
    }
}

@media screen and (max-width: 1024px) {
    .well a:hover{
      background: #000;
      color: #fff;
    }
}

@media screen and (max-width: 1024px) {
    .well2{
      width: 500px;
      margin-top: -30px;
      margin-left: -65px;
      padding:2rem 0;
      text-align: center;
    }
}

@media screen and (max-width: 1024px) {
    .well2 a{
      width: 200px;
      padding: 10px 80px;
      margin: auto 10px;
      border: 1px solid #000;
      font-size: 1rem;
      color: #000;
      transition: .5s;
    }
}

@media screen and (max-width: 1024px) {
    .well2 a:hover{
      background: #000;
      color: #fff;
    }
}

@media screen and (max-width: 1024px) {
    .wel2 {
        display: none;
    }
}
  </style>

<body>

  <article class="welcome">
            <div class="wel1">
              <ion-icon name="checkmark-sharp"></ion-icon>
              <h1>회원가입이 완료 되었습니다.</h1>
              <h3><b>{{new_member.username}}</b>님, 가입을 환영합니다.</h3>
            </div>
            <div class="wel2">
              <a class="home" href="/">홈으로</a>
              <a href="{% url 'zeronine:login' %}">로그인</a>
            </div>
            <div class="well">
              <a class="home" href="/">홈으로</a>
            </div>
            <div class="well2">
              <a href="{% url 'zeronine:login' %}">로그인</a>
            </div>
  </article>


</body>


{% endblock %}