config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zeronine.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

join/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('join_create/<int:id>/', join_create, name='join_create'),
    ]

post/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('post/', post, name='post'),
    path('post_write/', post_write, name='post_write'),
    path('post_detail/<int:pk>/', post_detail, name='post_detail'),
    path('post_delete/<int:pk>/', post_delete, name='post_delete'),
    path('post_modify/<int:pk>/', post_modify, name='post_modify'),
    path('comment_create/<int:article_pk>', comment_create, name='comment_create'),
    path('comment_delete/<int:comment_pk>', comment_delete, name='comment_delete'),
    path('search/', search, name='search'),
]

zeronine/urls.py
from django.urls import path, include
from .views import *

app_name = 'zeronine'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('product/', include('product.urls')),
    path('join/', include('join.urls')),
    path('zzim/', include('zzim.urls')),
    path('mypage/', include('mypage.urls')),
]

post/models.py
from django.db import models

# Create your models here.

post/forms.py
from django import forms
from .models import *


class PostForm(forms.Form):
    title = forms.CharField(error_messages = {'required':"제목을 입력해주세요."}, label = "제목", max_length=128)
    contents = forms.CharField(error_messages = {'required':"내용을 입력해주세요."}, label = "내용", widget = forms.Textarea)

class CommentForm(forms.Form):
    contents = forms.CharField(error_messages = {'required':"내용을 입력해주세요."}, label = "내용", widget = forms.Textarea)

post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from post.forms import PostForm, CommentForm
from zeronine.models import Category, Post, Comment

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404, HttpResponseRedirect

# Create your views here.
def post(request):
    current_category = None
    categories = Category.objects.all()

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('zeronine:login'))

    page = request.GET.get('page', '1')
    posts = Post.objects.all().order_by('-register_date')
    paginator = Paginator(posts, 5)

    try:
        posts = paginator.page(page)

    except PageNotAnInteger:
        posts = paginator.page(1)

    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    index = posts.number
    max_index = len(paginator.page_range)
    page_size = 5

    start_index = index - page_size if index > page_size else 1

    if index + page_size == max_index:
        end_index = max_index
    else :
        end_index = index + page_size if index <= max_index else max_index

    page_range = list(paginator.page_range[start_index-1:end_index])

    return render(request, 'post/post_list.html', {'posts':posts,
                                                   'page_range':page_range,
                                                   'max_index':max_index,
                                                   'page_size':page_size,
                                                   'current_category': current_category, 'categories': categories})

def post_write(request):
    current_category = None
    categories = Category.objects.all()

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('zeronine:login'))

    if request.method == "POST":
        form = PostForm(request.POST)

        if form.is_valid():
            post = Post()
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['contents']
            post.username = request.user
            post.save()

            return HttpResponseRedirect(reverse('zeronine:post'))

    else:
        form = PostForm()

    return render(request, 'post/post_write.html', {'form': form, 'current_category': current_category, 'categories': categories})

def post_detail(request, pk):
    current_category = None
    categories = Category.objects.all()

    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        raise Http404('게시글을 찾을 수 없습니다')
        # 게시물의 내용을 찾을 수 없을 때 내는 오류 message.

    comments = Comment.objects.filter(post_code=pk)

    return render(request, 'post/post_detail.html', {'post': post, 'comments': comments, 'current_category': current_category, 'categories': categories})

def search(request):
    current_category = None
    categories = Category.objects.all()
    posts = Post.objects.all().order_by('-register_date')

    q = request.POST.get('q', "")

    if q:
        posts = posts.filter(title__icontains=q)
        return render(request, 'post/search.html', {'posts': posts, 'q': q, 'current_category': current_category, 'categories': categories})

    else:
        return render(request, 'post/search.html', {'categories': categories})


def post_modify(request, pk):
    current_category = None
    categories = Category.objects.all()
    post = Post.objects.get(pk=pk)

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('zeronine:login'))

    if request.method == "POST":
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.username = request.user

        post.save()
        return redirect('zeronine:post')

    else:
        postForm = PostForm
        return render(request, 'post/post_modify.html', {'postForm':postForm, 'post':post, 'current_category': current_category, 'categories': categories})

def post_delete(request, pk):
    current_category = None
    categories = Category.objects.all()
    post = Post.objects.get(pk=pk)
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('zeronine:login'))

    if request.method == 'POST':
        post.delete()
        return redirect('zeronine:post')
    return render(request, 'post/post_delete.html', {'Post': post,
                                                     'current_category': current_category, 'categories': categories})

def comment_create(request, article_pk):

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = Comment()
            comment.content = form.cleaned_data['contents']
            comment.username = request.user
            comment.post_code = get_object_or_404(Post, pk=article_pk)
            comment.save()

            return HttpResponseRedirect(reverse('zeronine:post_detail', kwargs={'pk': article_pk}))
    else:
        form = CommentForm()

    return HttpResponseRedirect(reverse('zeronine:post_detail', kwargs={'pk': article_pk}))

def comment_delete(request, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)

    if request.method == "POST":
        comment.delete()

        return HttpResponseRedirect(reverse('zeronine:post_detail', kwargs={'pk': comment.post_code.pk}))

    return HttpResponseRedirect(reverse('zeronine:post_detail', kwargs={'pk': comment.post_code.pk}))

post/templates/post/post_delete.html
{% extends 'base.html' %}

{% block content %}
<br>
        <meta name="viewport" content="width=device-width, initial-scale=1">
<div class="row justify-content-center">
    <div class="col-md-7 panel panel-default">
        <div class="alert alert-info" style="background-color: #f7d7da; border: none">
            <b style="color: #721d09">게시글을 삭제하시겠습니까?</b>
        </div>
        <form action="" method="post">
        {% csrf_token %}
            <button style="background: #c43e34; border: black; float: right" class="btn btn-primary">삭제</button>
        </form>
        <a href="{% url 'zeronine:post' %}"><button style="background: darkgrey; border: black; float: right; margin-right: 10px;" class="btn btn-danger">취소</button></a>
    </div>
</div>
{% endblock %}

post/templates/post/post_detail.html
{% extends "base.html" %}

{% block content %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
<div class="card container my-3 justify-content-center" style="border: white">
    <!--제목,분류,작성일-->
    <div class="card-header">
        <strong>{{ post.title }}</strong><span></span>&nbsp;
        <span style="font-size: 14px;">{{ post.register_date|date:'Y.m.d. H:i' }}</span>
        {% if user == post.username %}
            <a href="{% url 'zeronine:post_delete' pk=post.post_code %}"><button style="background:#f7f7f7; border: none; color:black; float:right;" class="btn btn-primary"><b>삭제</b></button></a>
            <a href="{% url 'zeronine:post_modify' pk=post.post_code %}"><button style="background:#f7f7f7; border: none; color:black; float: right; margin-right: 0px;" class="btn btn-primary"><b>수정</b></button></a>
        {% endif %}
    </div>
    <div class="card-body">
        <div>
            <span>작성자 : {{ post.username }}</span>
        </div><hr>
        <div>
            {{ post.content }}
        </div>
    </div>
<br>
<br>
    <br>

<br>
<div class = "container" style="margin-top: 50px;">
<div class = "row">
    <div class = "col-md-12 comment-bg">
        <!--댓글 목록-->
    <div class = "comments-list">
        <h5 style="margin-bottom: 15px;"><b>댓글</b></h5>
            {% for comment in comments %}
            <div class = "media">
                <div class = "media-body">
                    <div class="name" style="font-size: 15px; margin-left: 1px;"><b> {{comment.username}}</b></div>
                    <div class="date" style="font-size: 12px; margin-bottom: 5px;">{{ comment.register_date }}</div>
                    <div class="content" style="font-size: 14px; margin-bottom: 5px;">{{comment.content}}</div>

                    <hr>
                </div>
                <hr>

                 <form method="POST" action ="{% url 'zeronine:comment_delete' comment_pk=comment.pk %}">
                  {% csrf_token %}
                     {% if user == comment.username %}
                     <div class="form-group">
                    <button type = "submit" class = "btn btn-primary " style="background: #F2F2F2; border: none; color:black; font-size: 12px; border: white; float: right; margin-top: 25px;">삭제</button>
                     </div>
                     {% endif %}
                 </form>

            </div>
             {% empty %}
       <h6 style="font-size:15px;"><b>아직 댓글이 없습니다.</b></h6><br><br>
            {% endfor %}
    </div>
         <!--댓글 작성-->
        <div class="row" style="margin-left: -2px;">
                    {% if errors %}
                <ul>
                    {% for error in errors %}
                    <li><div class = "alert alert-primary">{{error}}</div></li>
                    {% endfor %}
             </ul>
            {% endif %}
            <form method = "POST" action = "{% url 'zeronine:comment_create' article_pk=post.pk %}" class = "col-md-20 mx-auto">
               {% csrf_token %}
                <div class="form-group">
                    <p style="font-size: 14px;"><b>댓글 작성</b></p>
                    <textarea name="contents" placeholder="내용을 입력하세요." class="form-control" cols="160"></textarea>
                    <button type = "submit" class = "btn btn-primary " style="background: #637B46; border: white; float: right; margin-top: 20px;">등록</button>
                </div>
           </form>
                   <a href="{% url 'zeronine:post' %}"><button style="background: darkgrey; border: white; float: right; margin-top: -35.5px;" class="btn btn-primary">이전</button></a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

post/templates/post/post_list.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<style>


    .button1{
        background:none;
        border: none;

    }

@media screen and (min-width: 601px) {
    .search-icon{
        width: 30px;
        margin-left: -65px;
        color: #cccccc;
        margin-bottom: 1px;
    }
  }

@media screen and (max-width: 600px) {
    .search-icon{
        width: 20px;
        margin-left: -65px;
        color: #cccccc;
        margin-bottom: 1px;
    }
  }
    .plus{
        margin-bottom: 30px;
    }

    .inputbox {
        width: 180px;
        border: solid 1px;
        border-color: gainsboro;
        height: 35px;
    }

    @media screen and (max-width: 600px) {
    .inputbox {
        border: solid 1px;
        border-color: gainsboro;
        height: 35px;
        width: 120px;
    }
  }

@media screen and (min-width: 601px) {
    .table th {

    }
}

    @media screen and (max-width: 600px) {
    .table th {
       font-size: 13px;
    }
  }

@media screen and (min-width: 601px) {
    .table td {
        text-decoration: none;
        color: #111111;
    }
}

    @media screen and (max-width: 600px) {
    .table td {
       font-size: 13px;
       text-decoration: none;
    }
  }

    @media screen and (min-width: 601px) {
        .paging {
            margin-right: 45px;
        }
    }


    @media screen and (max-width: 600px) {
        .paging {
            margin-right: 50px;
        }
    }

.inputbox:focus {outline:1px solid #D8D8D8; padding:10px;}

.button1:focus {outline:none;}
</style>
<div class="container my-4">
<h3 style="margin-top:40px;"><b>자유게시판</b></h3>

    <a href="{% url 'zeronine:post_write' %}"><button class="btn btn-primary" style="float:right; background: #849160; border: white; border-radius:0px; font-size: 16px;">글쓰기</button></a>

    <form  style="float:right; margin-right: 6px;" action="{% url 'zeronine:search' %}" method="post">
      {% csrf_token %}
        <div class="plus">
        <input class="inputbox" type="search" aria-label="Search" name="q" value="{{q}}">
        <button class="button1" style="text-decoration: none;" type="submit"><img class="search-icon" style="margin-top: -2px;" src="https://cdn1.iconfinder.com/data/icons/hawcons/32/698956-icon-111-search-512.png"></button>
            </div>
      </form>

  <div class="row">
  <div class="col-12">
  </div>
  </div>

<div class="row mt-5" style="clear:both;">
  <div class="col-12">

    <table class="table">
      <thead class="thead" style="background: #f7f7f7">
          <colgroup>
      <col>
      <col style="width:20%;">
      <col span="3">
    </colgroup>
        <tr style="background: #f7f7f7">
          <th scope="col" style="width: 15%">번호</th>
          <th scope="col">제목</th>
          <th scope="col">작성자</th>
          <th scope="col">작성일</th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
        <tr>
          <th scope="row"><a style="text-decoration: none; color: #111111" href="{% url 'zeronine:post_detail' pk=post.post_code %}">{{ post.post_code }}</a></th>
          <td><a style="text-decoration: none; color: #111111" href="{% url 'zeronine:post_detail' pk=post.post_code %}">{{ post.title }}</a></td>
          <td>{{ post.username }}</td>
          <td>{{ post.register_date }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
                <br><ul class="paging justify-content-center">
                    {% if posts.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ posts.previous_page_number }}">이전으로</a>
                    </li>
                    {% endif %}
                    {% if posts.number > page_size|add:"1" %}
                      <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                      <li class="page-item"><span class="page-link">...</span></li>
                    {% endif %}
                  {% for page_number in page_range %}
                  {% if page_number == posts.number %}
                    <li class="page-item active" aria-current="page">
                      <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
                    </li>
                    {% endif %}
                  {% endfor %}
                  {% if posts.number|add:page_size < max_index %}
                    <li class="page-item"><span class="page-link">...</span></li>
                    <li class="page-item"><a class="page-link" href="?page={{max_index}}">{{max_index}}</a></li>
                  {% endif %}

                  {% if posts.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{posts.next_page_number}}">다음으로</a>
                  </li>
                  {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>

{% endblock %}

post/templates/post/post_modify.html
{% extends "base.html" %}

{% block content %}

<style>
@media screen and (min-width: 600px) {
    .modify textarea[name="textare"] {
        margin-left: 55px;
        margin-top: -25px;
    }
}

@media screen and (max-width: 600px) {
    .modify textarea[name="textare"] {
        margin-left: 55px;
        margin-top: -25px;
        width: 250px;
    }
}

@media screen and (min-width: 600px) {
    .modify input[name="title"] {

    }
}

@media screen and (max-width: 600px) {
    .modify input[name="title"] {
        width: 120px;
        margin-left: 8px;
    }
}
</style>

    <meta name="viewport" content="width=device-width, initial-scale=1">
<div class="card container my-3 justify-content-center" style="border: white">
        <h3 style="margin-top:20px; margin-bottom: 30px;"><b>게시글 수정</b></h3>
   <form method="POST">
         <article class="modify">
     {% csrf_token %}
      <div class="card-header">
         <strong>제목 : &nbsp;</strong>
         <input type="text" value="{{ post.title }}" name="title">
            &nbsp;<span style="font-size: 14px;">{{ post.register_date|date:'Y.m.d. H:i' }}</span>
        </div>
      <div class="card-body">
            <div>
                <span>작성자 : <b>{{ post.username }}</b></span>
            </div><hr>
          <div><strong>내용: &nbsp;</strong></div>
           <textarea name="textare" cols=45 rows=10>{{ post.content }}</textarea>
     <br>
     <br>
      </div>
             <input class="btn btn-dark" type="submit" style="background-color: #637B46; border: white; float: right" value="수정"></article></form>
        <div><a href="{% url 'zeronine:post' %}"><button style="background: #848484; border: white; float: right; margin-top:-36px; margin-right: 65px;" class="btn btn-danger">이전</button></a></div>
  </form>
</div>
{% endblock %}

post/templates/post/post_write.html
{% extends "base.html" %}

{% block content %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
<div class="container my-4">
    <h3 style="margin-top:40px; margin-bottom: -15px;"><b>게시글 작성</b></h3>
    <div class="row mt-5">
  <div class="col-12">
    <form method="POST" action="{% url 'zeronine:post_write' %}">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}"><b>{{ field.label }}</b></label>
        {% ifequal field.name 'contents' %}
  <textarea name="{{field.name}}" placeholder="내용을 입력하세요." class="form-control" cols="160" rows="10"></textarea>
    {% else %}
    <input type="{{ field.field.widget.input_type }}" class="form-control" id='{{ field.id_for_label }}'
        placeholder="제목을 입력하세요." name='{{ field.name }}'>
            {% endifequal %}
          </div>

      {% if field.errors %}
      <span style="color: #637B46;">{{ field.errors }}</span>
      {% endif %}
      {% endfor %}
      <button type="submit" action="{% url 'zeronine:post_write' %}" class="btn btn-primary" style="float: right; background: #637B46; border: white">업로드</button>
        <a href="{% url 'zeronine:post' %}"><button type ="button" class = "btn btn-primary" style = "float:right; margin-right:10px; background: #848484; border: white;">이전</button></a>
    </form>
  </div>
</div>
</div>
{% endblock %}

post/templates/post/search.html
{% extends 'base.html' %}

{% block content %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if not posts %}

<h5 style="text-align: center; margin-top: 50px;"><b>검색 결과가 없습니다</b></h5></div>
        <a href="{% url 'zeronine:post' %}">
            <div style="text-align: center;"><button style="margin-top: 20px; font-size:15px; margin-bottom: 30px; background: #cccccc; border: white; border-radius:0px;" class="btn btn-primary">이전으로</button></div></a>

    {% else %}

        {% for post in posts.all %}
        <br>
        <div class="container" style="width: 100%">
            <div class="card">
                <div class="card-body">
                    <h5>{{ post.title }}</h5>
                    <p>{{ post.pub_date | date:"Y-m-d" }}</p>
                    <p>{{ post.summary }}<a href="{% url 'zeronine:post_detail' post.post_code %}"> ...자세히 보기</a></p>
                </div>
            </div>
        </div>
        <br>
        {% endfor %}

    {% endif %}

{% endblock %}