config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zeronine.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

join/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('join_create/<int:id>/', join_create, name='join_create'),
    ]

product/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('product_upload/', product_upload, name='product_upload'),
    path('product_search/', product_search, name='product_search'),
    ]

zeronine/urls.py
from django.urls import path, include
from .views import *

app_name = 'zeronine'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('product/', include('product.urls')),
    path('join/', include('join.urls')),
    path('zzim/', include('zzim.urls')),
    path('mypage/', include('mypage.urls')),
]

product/models.py
from django.db import models

# Create your models here.

product/forms.py
from django import forms
from django.forms import NumberInput

from zeronine.models import *

class ProductForm(forms.Form):
    name = forms.CharField(error_messages={'required': "상품명을 입력하세요."}, max_length=32, label="상품명")
    benefit = forms.CharField(error_messages={'required': "공동구매 취지를 입력해주세요."}, label="공동구매 취지", widget=forms.Textarea)
    detail = forms.CharField(error_messages={'required': "상품 설명을 입력하세요"}, label="상품 설명")
    target_price = forms.IntegerField(error_messages={'required': "목표 금액을 입력하세요."}, label="목표금액")
    photo = forms.ImageField(error_messages={'required': "상세 이미지를 첨부해주세요."}, label="상세이미지")
    start_date = forms.DateField(error_messages={'required': "모집 시작일을 선택해주세요."}, label="모집 시작일", widget=NumberInput(attrs={'type': 'date'}))
    due_date = forms.DateField(error_messages={'required': "모집 마감일을 선택해주세요."}, label="모집 마감일", widget=NumberInput(attrs={'type': 'date'}))
    category_code = forms.ModelChoiceField(error_messages={'required': "카테고리를 선택해주세요."}, label="카테고리", queryset=Category.objects.all())
    kakao_link = forms.CharField(error_messages={'required': "채팅방 링크를 입력하세요."}, max_length=100, label="카카오톡 링크")

class PhotoForm(forms.Form):
    image = forms.ImageField(error_messages={'required': "상세 이미지를 첨부해주세요."}, label="상세이미지")

class OptionForm(forms.Form):
    option_name = forms.CharField(error_messages={'required': "옵션명을 입력하세요."}, max_length=32, label="옵션명")
    second_option_name = forms.CharField(error_messages={'required': "옵션명을 입력하세요."}, max_length=32, label="옵션명",required=False)

class ValueForm(forms.Form):
    value_name = forms.CharField(error_messages={'required': "옵션값을 입력하세요."}, max_length=32, label="옵션명")
    option_price = forms.IntegerField(error_messages={'required': "옵션명을 입력하세요."}, label="옵션추가비용")
    value_name2 = forms.CharField(error_messages={'required': "옵션값을 입력하세요."}, max_length=32, label="옵션명",required=False)
    option_price2 = forms.IntegerField(error_messages={'required': "옵션명을 입력하세요."}, label="옵션추가비용",required=False)

class DesignatedForm(forms.Form):
    price = forms.IntegerField(error_messages={'required': "옵션명을 입력하세요."}, label="가격")

product/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from zeronine.models import *
from .forms import *

# Create your views here.
def product_upload(request):
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    photos = Photo.objects.all()
    designated_object = Designated.objects.all()
    options = Option.objects.all()
    slug = Product.slug

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)

        if form.is_valid():
            product = Product()
            product.name = form.cleaned_data['name']
            product.benefit = form.cleaned_data['benefit']
            product.detail = form.cleaned_data['detail']
            product.target_price = form.cleaned_data['target_price']
            product.start_date = form.cleaned_data['start_date']
            product.due_date = form.cleaned_data['due_date']
            product.category_code = form.cleaned_data['category_code']
            product.image = request.FILES['photo']
            product.username = request.user
            product.slug = slug
            product.kakao_link = form.cleaned_data['kakao_link']
            product.save()

        for img in request.FILES.getlist('image'):
            photo = Photo()
            photo.product_code = product
            photo.photo = img
            photo.save()

    if request.method == "POST":
        form = OptionForm(request.POST)

        if form.is_valid():
            option = Option()
            option.name = request.POST.get('option_name')
            option.product_code = product
            option.save()


    if request.method == "POST":
        form = ValueForm(request.POST)

        if form.is_valid():
            for value_name, option_price in zip(request.POST.getlist('value_name'), request.POST.getlist('option_price')):
                value = Value()
                value.name = value_name
                value.option_code = option
                value.product_code = product
                value.extra_cost = option_price
                value.save()


    if request.method == "POST":
        form = OptionForm(request.POST)

        if form.is_valid():
            option = Option()
            option.name = request.POST.get('second_option_name')
            option.product_code = product
            option.save()


    if request.method == "POST":
        form = ValueForm(request.POST)

        if form.is_valid():
            for value_name2, option_price2 in zip(request.POST.getlist('value_name2'), request.POST.getlist('option_price2')):
                value = Value()
                value.name = value_name2
                value.option_code = option
                value.product_code = product
                value.extra_cost = option_price2
                value.save()

    if request.method == "POST":
        form = DesignatedForm(request.POST)

        if form.is_valid():
            designated = Designated()
            designated.price = form.cleaned_data['price']
            designated.product_code = product
            designated.rep_price = True
            designated.save()


            return render(request, 'zeronine/list.html', {'form': form,
                                                          'current_category': current_category,
                                                          'photos':photos,
                                                          'options':options,
                                                          'products': products,
                                                          'categories': categories,
                                                          'slug': slug, })
    else:
        form = ProductForm()

    return render(request, 'product/product_upload.html',{'form': form,
                                                          'current_category': current_category,
                                                          'photos':photos,
                                                          'options':options,
                                                          'products': products,
                                                          'categories': categories})

def product_search(request):
    current_category = None
    categories = Category.objects.all()
    designated_object = Designated.objects.all()
    products = None
    query = None

    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query))

    return render(request, 'product/product_search.html', {'designated_object':designated_object, 'current_category':current_category, 'categories':categories, 'query':query, 'products':products})

product/templates/product/product_search.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.my_search_text {
    padding-top: 20px;
}

.paragraph--type--card-narrow-row {
 display: flex;
 align-items: flex-start;
 justify-content: left;
 flex-flow: row wrap;
}

 .card-narrow {
  width: 300px;
  height: 370px;
  border: 1px solid #ccc;
  margin: 20px;
  display: flex;
  flex-direction: column;
  }

 @media (max-width: 767px) {
     .card-narrow {
         margin-left: -26px;
     }

     .card-narrow-image {
         height: 280px;
     }

     .card-narrow h3 {
         margin: 0;
         padding: 10px 0;
         text-align: center;
         line-height: 1.2;
         font-family: "Raleway", Arial, Helvetica, sans-serif;
         width: 100%;
         display: inline-block;
         vertical-align: middle;
         cursor: pointer;
         background-color: #eee;
     }

     .card-narrow p {
         padding: 0 10px;
         font-family: Arial, Helvetica, sans-serif;
         margin-bottom: 0;
     }

     .card-narrow-content {
         flex: 1 1 180px;

     }

     .card-narrow {
         background: #fff;
         border-radius: 2px;
         display: inline-block;
         position: relative;

     }
 }
</style>

<link rel="stylesheet" href="{% static 'style.css' %}">

<p class="text-center my_search_text" style="margin-top: 15px; font-size: 17px"><b>'{{query}}'에 대한 검색 결과</b></p>

    {% if not products %}

    <h6 class="my_search_text" style="text-align: center; margin-top: 20px;">검색 결과가 없습니다.</h6>

    {% else %}

        <div class="container">
            <div class="paragraph--type--card-narrow-row" style="margin-left: 50px; margin-top: 23px;">
            {% for product in products %}
                <div class="card-narrow">
                      <div class="card-narrow-image"><a href="{{product.get_absolute_url}}">
                          <img style="margin-top:20px; width: 240px; height: 260px; margin-left:30px;" src="{{product.image.url}}" alt="상품 이미지"></a>
                      </div>
                        <div class="card-narrow-content" style="margin-top:20px; justify-content: center; text-align: center"> <b style="font-size: 17px;">{{ product.name }}</b>
                             {% for designated in designated_object %}
                              {% if designated.product_code.product_code == product.product_code %}
                              {% load humanize %}
                            <p style="margin-top: 4px;">{{designated.price | floatformat:'0' | intcomma }}원</p>
                        </div>
                   </div>
            {% endif %}
            {% endfor %}
        {% endfor %}
    {% endif %}
</div>
</div>
{% endblock %}

product/templates/product/uploadlist_modify.html
{% extends "base.html" %}

{% block content %}

<style>
#att_zone {
  min-height: 150px;
  padding: 10px;
  border: 1px solid #D8D8D8;
  margin-top: 10px;
}

#att_zone:empty:before {
  content: attr(data-placeholder);
  color: #999;
  font-size: .9em;
}

#thumbnail {
  min-height: 170px;
  padding: 10px;
  border: 1px solid #D8D8D8;
  margin-top: 10px;
}

#thumbnail:empty:before {
  content: attr(data-placeholder);
  color: #999;
  font-size: .9em;
}

</style>

<div class="container my-4">
    <h3 style="margin-top:40px; margin-bottom: 60px; text-align: center"><b>공동구매 상품 등록</b></h3>
    <div class="row mt-5">
    <div class="col-12">
    <form method="POST" action="{% url 'zeronine:product_upload' %}" enctype="multipart/form-data">
      {% csrf_token %}
      {% if field.errors %}
            <span style="color: #637B46;">{{ field.errors }}</span>
      {% endif %}
        <div class="form-group row">
            <label for="name" class="col-sm-2 col-form-label"><b>상품명</b></label>
            <div class="col-sm-10">
            <input type="text" class="form-control" name="name" id="name"
                   value="{{ form.name.value }}" placeholder="상품명을 입력하세요.">
            </div>
        </div>


        <div class="form-group row">
            <label for="category_code" class="col-sm-2 col-form-label"><b>카테고리</b></label>
            <div class="col-sm-10">
                <select type="text" class="form-control" name="category_code" id="category_code" value="{{ form.category_code }}</select>
            </div>
        </div>

        <div class="form-group row">
            <label for="price" class="col-sm-2 col-form-label"><b>상품가격</b></label>
            <div class="col-sm-10">
            <input type="text" class="form-control" name="price" id="price"
                   value="{{ form.price }}" placeholder="가격을 입력하세요.">
            </div>
        </div>

        <div class="form-group row" style="margin-right: -100px; margin-bottom: 27px">
            <label for="option_name" class="col-sm-2 col-form-label"><b>옵션</b></label>
        <!-- Button trigger modal -->
        <button type="button" style="background:#F2F2F2; color:#585858; border-color: #D8D8D8; margin-top: 10px;" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" >
          상품 옵션 지정하기
        </button>
            </div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">상품 옵션 지정하기</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>


        <br>


          <div class="form-row">
            <div class="form-group col-md-9" style="margin-left: 65px;">
            <label for="option_name" class="col-form-label"><b>옵션명</b></label>
            <input type="text" class="form-control text-align: center;" name="option_name" id="option_name" value="{{ form.option_name.value|default_if_none:'' }}" placeholder="옵션명을 입력하세요.">{{optionForm.option_name}}
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4" style="margin-left: 65px;">
              <label for="value_name" class="col-form-label"><b>옵션값</b></label>
               <input type="text" class="form-control" name="value_name" id="value_name" value="{{ form.value_name.value|default_if_none:'' }}" placeholder="옵션값명을 입력하세요.">
            </div>
            <div class="form-group col-md-5">
              <label for="option_price" class="col-form-label"><b>옵션추가가격</b></label>
               <input type="text" class="form-control" name="option_price" id="option_price" value="{{ form.option_price.value|default_if_none:'' }}" placeholder="옵션 추가 가격을 입력하세요.">
            </div>
          </div>

           <div class="form-row">
            <div class="form-group col-md-4" style="margin-left: 65px;">
              <label for="second_value" class="col-form-label"><b>옵션값2</b></label>
               <input type="text" class="form-control" name="second_value" id="second_value" value="{{ form.second_value.value|default_if_none:'' }}" placeholder="옵션값명을 입력하세요.">
            </div>
            <div class="form-group col-md-5">
              <label for="second_option_price" class="col-form-label"><b>옵션추가가격</b></label>
               <input type="text" class="form-control" name="second_option_price" id="second_option_price" value="{{ form.second_option_price.value|default_if_none:'' }}" placeholder="옵션 추가 가격을 입력하세요.">
            </div>
          </div>

           <div class="form-row">
            <div class="form-group col-md-4" style="margin-left: 65px;">
              <label for="third_value" class="col-form-label"><b>옵션값3</b></label>
               <input type="text" class="form-control" name="third_value" id="third_value" value="{{ form.third_value.value|default_if_none:'' }}" placeholder="옵션값명을 입력하세요.">
            </div>
            <div class="form-group col-md-5">
              <label for="third_option_price" class="col-form-label"><b>옵션추가가격</b></label>
               <input type="text" class="form-control" name="third_option_price" id="third_option_price" value="{{ form.third_option_price.value|default_if_none:'' }}" placeholder="옵션 추가 가격을 입력하세요.">
            </div>
          </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">저장</button>
      </div>
    </div>
  </div>
</div>
        <div class="form-group row">
            <label for="benefit" class="col-sm-2 col-form-label"><b>공동구매 취지</b></label>
            <div class="col-sm-10" >
            <input type="text" class="form-control" name="benefit" id="benefit"
                   value="{{ form.benefit.value }}" placeholder="상품명을 입력하세요.">
            </div>
        </div>

        <div class="form-group row">
            <label for="detail" class="col-sm-2 col-form-label"><b>상세설명</b></label>
            <div class="col-sm-10" >
            <input type="text" class="form-control" name="detail" id="detail"
                   value="{{ form.detail.value }}" placeholder="상품의 상세 설명을 입력하세요.">
            </div>
        </div>


        <div class="form-group row">
            <label for="target_price"  class="col-sm-2 col-form-label"><b>목표금액</b></label>
            <div class="col-sm-10">
            <input type="target_price" class="form-control" name="target_price" id="target_price"
                   value="{{ form.target_price.value|default_if_none:'' }}" placeholder="공동구매 달성을 위한 목표 금액을 입력하세요.">
            </div>
        </div>

        <div class="form-group row">
            <label for="start_date" class="col-sm-2 col-form-label"><b>모집 시작일</b></label>
            <div class="col-sm-10">
            <input type="date" class="form-control" id="start_date" name={{form.start_date}}
            </div>
        </div>

        <div class="form-group row">
            <label for="due_date" class="col-sm-2 col-form-label"><b>모집 마감일</b></label>
            <div class="col-sm-10">
            <input type="date" class="form-control" id="due_date"  name={{form.due_date}}
            </div>
        </div>

        <div class="form-group row">
            <label for="kakao_link" class="col-sm-2 col-form-label"><b>카카오톡 링크</b></label>
            <div class="col-sm-10">
            <input type="text" class="form-control" name="kakao_link" id="kakao_link"
                   value="{{ form.kakao_link.value|default_if_none:'' }}" placeholder="카카오톡 채팅방 링크를 입력하세요.">
            </div>
        </div>

       <div class="form-group row">
            <label for="photo" class="col-sm-2 col-form-label"><b>썸네일</b></label>
            <div class="col-sm-10">
            <input type="file" class="form-control" name="photo" id="photo" onchange="setThumbnail(event);" value="{{ form.photo.value|default_if_none:'' }}"/>
                <div id="thumbnail" class="thumbnail" data-placeholder='사진을 첨부 하려면 파일 선택 버튼을 클릭하세요.'></div>
            </div>
        </div>

<script>

function setThumbnail(event) {
    var reader = new FileReader();
    reader.onload = function(event) {
        var img = document.createElement("img");
        var btn_style = 'width:140px;height:140px;display:inline-block;position:absolute;font-size:16px;'
                  + 'z-index:none;background-color:white;border:1px solid #D8D8D8; margin-top:5px;margin-left:5px;';
        img.setAttribute('style', btn_style);
        img.setAttribute("src", event.target.result);
        document.querySelector("div#thumbnail").appendChild(img);
    };

    reader.readAsDataURL(event.target.files[0]); }
</script>


        <div class="form-group row">
            <label for="btnAtt" class="col-sm-2 col-form-label"><b>상세이미지</b></label>
            <div class="col-sm-10">
             <input type='file' class="form-control" name="image" id='btnAtt' multiple='multiple' value="{{ form.image.value|default_if_none:'' }}"/>
             <div class='att_zone' id='att_zone' data-placeholder='사진을 첨부 하려면 파일 선택 버튼을 클릭하거나 파일을 드래그 앤 드롭 하세요.'></div>
             </div>
        </div>

 <script>
( /* att_zone : 이미지들이 들어갈 위치 id, btn : file tag id */
  imageView = function imageView(att_zone, btn){

    var attZone = document.getElementById(att_zone);
    var btnAtt = document.getElementById(btn)
    var sel_files = [];

    // 이미지와 체크 박스를 감싸고 있는 div 속성
    var div_style = 'display:inline-block;position:relative;'
                  + 'width:140px;height:140px;margin:5px;border:1px solid #D8D8D8;z-index:1';
    // 미리보기 이미지 속성
    var img_style = 'width:100%;height:100%;z-index:none';
    // 이미지안에 표시되는 체크박스의 속성
    var chk_style = 'width:30px;height:30px;position:absolute;font-size:16px;'
                  + 'right:0px;bottom:0px;z-index:999;background-color:white; color:#DF0101; line-height:15px; font-weight:bold;';
    var btn_style = 'width:30px;height:30px;position:absolute;font-size:16px;'
                  + 'right:0px;bottom:0px;z-index:999;background-color:white; border:1px solid #BDBDBD; color:#DF0101; line-height:15px; font-weight:bold;';

    btnAtt.onchange = function(e){
      var files = e.target.files;
      var fileArr = Array.prototype.slice.call(files)
      for(f of fileArr){
        imageLoader(f);
      }
    }


    // 탐색기에서 드래그앤 드롭 사용
    attZone.addEventListener('dragenter', function(e){
      e.preventDefault();
      e.stopPropagation();
    }, false)

    attZone.addEventListener('dragover', function(e){
      e.preventDefault();
      e.stopPropagation();

    }, false)

    attZone.addEventListener('drop', function(e){
      var files = {};
      e.preventDefault();
      e.stopPropagation();
      var dt = e.dataTransfer;
      files = dt.files;
      for(f of files){
        imageLoader(f);
      }

    }, false)


    /*첨부된 이미지들을 배열에 넣고 미리보기 */
    imageLoader = function(file){
      sel_files.push(file);
      var reader = new FileReader();
      reader.onload = function(ee){
        let img = document.createElement('img')
        img.setAttribute('style', img_style)
        img.src = ee.target.result;
        attZone.appendChild(makeDiv(img, file));
      }

      reader.readAsDataURL(file);
    }

    /*첨부된 파일이 있는 경우 checkbox와 함께 attZone에 추가할 div를 만들어 반환 */
    makeDiv = function(img, file){
      var div = document.createElement('div')
      div.setAttribute('style', div_style)

      var btn = document.createElement('input')
      btn.setAttribute('type', 'button')
      btn.setAttribute('value', 'X')
      btn.setAttribute('delFile', file.name);
      btn.setAttribute('style', chk_style);
      btn.setAttribute('style', btn_style);
      btn.onclick = function(ev){
        var ele = ev.srcElement;
        var delFile = ele.getAttribute('delFile');
        for(var i=0 ;i<sel_files.length; i++){
          if(delFile== sel_files[i].name){
            sel_files.splice(i, 1);
          }
        }

        dt = new DataTransfer();
        for(f in sel_files) {
          var file = sel_files[f];
          dt.items.add(file);
        }
        btnAtt.files = dt.files;
        var p = ele.parentNode;
        attZone.removeChild(p)
      }
      div.appendChild(img)
      div.appendChild(btn)
      return div
    }
  }
)('att_zone', 'btnAtt')

</script>
  <button class="btn btn-primary">제출</button>
        </a>
        </div>
        </form>

    </div>
  </div>
</div>
{% endblock %}