config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zeronine.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

join/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('join_create/<int:id>/', join_create, name='join_create'),
    ]

mypage/urls.py
from django.urls import path
import mypage.views

urlpatterns = [
    path('mypage_list/', mypage.views.mypage_list, name='mypage_list'),
    path('profile/delete/', mypage.views.profile_delete_view, name='profile_delete'),
    path('mypage_pwchange/', mypage.views.password_edit_view, name='mypage_pwchange'),
    path('test/', mypage.views.test, name='test'),
    path('mypage_joinlist/', mypage.views.mypage_joinlist, name='mypage_joinlist'),
    path('mypage_zzimlist/', mypage.views.mypage_zzimlist, name='mypage_zzimlist'),
    path('zzim_delete/<int:pk>/', mypage.views.zzim_delete, name='zzim_delete'),
    path('mypage_uploadlist/', mypage.views.mypage_uploadlist, name='mypage_uploadlist'),
    path('mypage_delete/<int:pk>/', mypage.views.mypage_delete, name='mypage_delete'),
    ]

zeronine/urls.py
from django.urls import path, include
from .views import *

app_name = 'zeronine'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('product/', include('product.urls')),
    path('join/', include('join.urls')),
    path('zzim/', include('zzim.urls')),
    path('mypage/', include('mypage.urls')),
]

mypage/models.py
from django.db import models

# Create your models here.

mypage/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import check_password

class MemberForm(forms.Form):
    name = forms.CharField(error_messages = {'required':"아이디 입력해주세요."}, label = "아이디", max_length=128)
    password = forms.CharField(error_messages = {'required':"비밀번호를 입력해주세요."}, label = "비밀번호", widget = forms.Textarea)
    email = forms.EmailField(error_messages = {'required':"이메일을 입력해주세요."}, label = "이메일", max_length=128)
    phone = forms.CharField(error_messages = {'required':"전화번호를 입력해주세요."}, label = "전화번호", max_length=64)

class CheckPasswordForm(forms.Form):
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput(
        attrs={'class': 'form-control', }),
                               )

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = self.user.password

        if password:
            if not check_password(password, confirm_password):
                self.add_error('password', '비밀번호가 일치하지 않습니다.')

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = '현재 비밀번호'
        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control',
            'autofocus': False,
        })
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
        })

mypage/views.py
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from mypage.forms import *
from zeronine.models import *

# Create your views here.

def mypage_list(request):
   current_category = None
   categories = Category.objects.all()
   member = Member.objects.all()

   if not request.user.is_authenticated:
       return HttpResponseRedirect(reverse('zeronine:login'))

   if request.method == "POST":
       for m in member:
           m.name = request.POST['name']
           m.phone = request.POST['userphone']
           m.email = request.POST['useremail']
           m.username = request.user
           m.save()
       return redirect('zeronine:mypage_list')

   else:
       memberForm = MemberForm
       return render(request, 'mypage/mypage_list.html', {'memberForm':memberForm, 'member':member, 'current_category': current_category, 'categories': categories})


def profile_delete_view(request):
    current_category = None
    categories = Category.objects.all()
    member = Member.objects.all()

    if request.method == 'POST':
        password_form = CheckPasswordForm(request.user, request.POST)

        if password_form.is_valid():
            request.user.delete()
            logout(request)
            messages.success(request, '회원탈퇴가 완료되었습니다.')
            return redirect('zeronine:mypage_list')

    else:
        password_form = CheckPasswordForm(request.user)

    return render(request, 'mypage/profile_delete.html', {'password_form': password_form, 'member':member, 'current_category': current_category, 'categories': categories})

@login_required
def password_edit_view(request):
    current_category = None
    categories = Category.objects.all()
    member = Member.objects.all()

    if request.method == 'POST':
        password_change_form = CustomPasswordChangeForm(request.user, request.POST)

        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)

            return redirect('zeronine:mypage_list')

    else:
        password_change_form = CustomPasswordChangeForm(request.user)

    return render(request, 'mypage/mypage_pwchange.html', {'password_change_form': password_change_form, 'member':member, 'current_category': current_category, 'categories': categories})

def test(request):
    current_category = None
    categories = Category.objects.all()
    member = Member.objects.all()
    join_objects = Join.objects.all()
    join_detail_objects = JoinDetail.objects.all()
    products = Product.objects.all()
    designated_object = Designated.objects.filter(rep_price='True')
    element_object = Element.objects.all()
    value_object = Value.objects.all()

    return render(request, 'mypage/test.html', {'member':member,
                                                           'join_objects':join_objects,
                                                           'join_detail_objects': join_detail_objects,
                                                           'current_category': current_category,
                                                           'categories': categories,
                                                           'designated_object': designated_object,
                                                           'element_object': element_object,
                                                           'value_object': value_object,
                                                           'products': products})

def mypage_joinlist(request):
    current_category = None
    categories = Category.objects.all()
    member = Member.objects.all()
    join_objects = Join.objects.all()
    join_detail_objects = JoinDetail.objects.all()
    products = Product.objects.all()
    designated_object = Designated.objects.filter(rep_price='True')
    element_object = Element.objects.all()
    value_object = Value.objects.all()

    return render(request, 'mypage/mypage_joinlist.html', {'member':member,
                                                           'join_objects':join_objects,
                                                           'join_detail_objects': join_detail_objects,
                                                           'current_category': current_category,
                                                           'categories': categories,
                                                           'designated_object': designated_object,
                                                           'element_object': element_object,
                                                           'value_object': value_object,
                                                           'products': products})

def mypage_zzimlist(request):
    zzim = Zzim.objects.all()
    current_category = None
    categories = Category.objects.all()
    member = Member.objects.all()
    join_objects = Join.objects.all()
    join_detail_objects = JoinDetail.objects.all()
    products = Product.objects.all()
    designated_object = Designated.objects.filter(rep_price='True')
    element_object = Element.objects.all()
    value_object = Value.objects.all()

    return render(request, 'mypage/mypage_zzimlist.html', {'member':member,
                                                           'join':join_objects,
                                                           'join_detail': join_detail_objects,
                                                           'current_category': current_category,
                                                           'categories': categories,
                                                           'designated_object': designated_object,
                                                           'element_object': element_object,
                                                           'value_object': value_object,
                                                           'products': products,
                                                           'zzim':zzim,})

def zzim_delete(request, pk):
    zzim = Zzim.objects.get(pk=pk)
    current_category = None
    categories = Category.objects.all()
    member = Member.objects.all()
    join_objects = Join.objects.all()
    join_detail_objects = JoinDetail.objects.all()
    products = Product.objects.all()
    designated_object = Designated.objects.filter(rep_price='True')
    element_object = Element.objects.all()
    value_object = Value.objects.all()

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('zeronine:login'))

    if request.method == 'POST':
        zzim.delete()
        return redirect('zeronine:mypage_zzimlist')

    return render(request, 'mypage/mypage_zzimlist.html', {'zzim': zzim,
                                                           'categories': categories,
                                                           'member': member,
                                                           'join': join_objects,
                                                           'join_detail': join_detail_objects,
                                                           'current_category': current_category,
                                                           'designated_object': designated_object,
                                                           'element_object': element_object,
                                                           'value_object': value_object,
                                                           'products': products,
                                                           'zzim': zzim,
                                                           })

def mypage_uploadlist(request):
    current_category = None
    categories = Category.objects.all()
    member = Member.objects.all()
    join_object = Join.objects.all()
    join_detail_objects = JoinDetail.objects.all()
    product_object = Product.objects.all()
    designated_object = Designated.objects.filter(rep_price='True')
    element_object = Element.objects.all()
    value_object = Value.objects.all()

    return render(request, 'mypage/mypage_uploadlist.html', {'member': member,
                                                             'join_object': join_object,
                                                             'join_detail_objects': join_detail_objects,
                                                             'current_category': current_category,
                                                             'categories': categories,
                                                             'designated_object': designated_object,
                                                             'element_object': element_object,
                                                             'value_object': value_object,
                                                             'product_object': product_object})

def mypage_delete(request, pk):
    product = Product.objects.get(pk=pk)
    current_category = None
    categories = Category.objects.all()
    member = Member.objects.all()
    join_object = Join.objects.all()
    join_detail_objects = JoinDetail.objects.all()
    product_object = Product.objects.all()
    designated_object = Designated.objects.filter(rep_price='True')
    element_object = Element.objects.all()
    value_object = Value.objects.all()

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('zeronine:login'))

    if request.method == 'POST':
        product.delete()
        return redirect('zeronine:mypage_uploadlist')

    return render(request, 'mypage/mypage_uploadlist.html', {'member': member,

mypage/templates/mypage/mypage_joinlist.html
{% extends "base.html" %}
{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
    table {border-collapse:collapse; width:100%;}
table a {color:#333; text-decoration:none;}
 .table-wrap table.board {
    font-family:'Noto Sans KR';
    text-align: center; }
.ellipsis, .subject{text-align:left;}

.table-wrap table {
  position: relative;
  line-height: 1.4;
  table-layout: fixed; }
  .table-wrap table::before {
    content: "";
    width: 100%;
    height: 1px;
    background-color: #000;
    position: absolute;
    top: 0;
    left: 0; }
  .table-wrap table thead th {
    border: 1px solid #ddd;
    border-bottom: 0;
    background-color: #f9f9f9;
    padding: 20px;
    color: #222;
    font-size: .9rem;
    font-weight: 400; }
    .table-wrap table thead th:first-child {
      border-left: 0; }
    .table-wrap table thead th:last-child {
      border-right: 0; }
  .table-wrap table tbody th {
    border: 1px solid #ddd;
    background-color: #fcfcfc;
    padding: 20px;
    font-size: .8rem;
    font-weight: 400;
    color: #222; }
    .table-wrap table tbody th:first-child {
      border-left: 0; }
    .table-wrap table tbody th:last-child {
      border-right: 0; }
    .table-wrap table tbody th .list.dash > li {
      padding-left: 15px; }
      .table-wrap table tbody th .list.dash > li::before {
        left: 0; }
  .table-wrap table tbody td {
    border: 1px solid #ddd;
    padding: 20px;
    font-size: .8rem;
    font-weight: 400;
    background-color: #fff; }
    .table-wrap table tbody td:first-child {
      border-left: 0; }
    .table-wrap table tbody td:last-child {
      border-right: 0; }

@media (max-width: 767px) {
    .table-wrap .board colgroup,
    .table-wrap .board thead {
        display: none;
    }

    .table-wrap .board tbody tr {
        border-bottom: 1px solid #dcdbdb;
        padding: 15px;
        display: block;
        overflow: hidden;
    }

    .table-wrap .board tbody tr td {
        display: none;
        padding: 0;
        border: 0;
    }

    .table-wrap .board tbody tr td.subject2 {
        display: block;
        font-weight: 700;
        color: #333;
        margin-bottom: 5px;
    }

    .table-wrap .board tbody tr td.subject > a {
        font-size: .9rem;
    }

    .table-wrap .board tbody tr {
        font-weight: 700;
        color: #333;
        margin-bottom: 5px;
        text-align: left;
        float: left;
        display: inline-block;
    }

    .table-wrap .board tbody tr td.bookname > a {
        font-size: .9rem;
    }

    .table-wrap .board tbody tr {
        display: inline-block;
        float: left;
        margin-left: 10px;
    }

    .table-wrap .board tbody tr td.date, .table-wrap .board tbody tr td.hit, .table-wrap .board tbody tr td.option, .table-wrap .board tbody tr td.name, .table-wrap .board tbody tr td.link2, .table-wrap .board tbody tr td.image {
        display: block;
        float: left;
        text-align: left;
        margin-right: 16px;
        margin-top: 1px;
        word-spacing: 12px;
        line-height: 15px;
    }

    .table-wrap .board tbody tr td.date::before {
        content: "가격 : ";
    }

    .table-wrap .board tbody tr td.hit::before {
        content: "수량 : ";
    }

    .table-wrap .board tbody tr td.option::before {
        content: "옵션 : ";
    }

    .table-wrap .board tbody tr td.image::before {
        content: "";
    }


    .table-wrap .board tbody tr td.name::before {
        content: "참여일자 : ";
    }

    .table-wrap .board tbody tr td.link2::before {
        content: "채팅방 링크 : ";
    }
}
</style>

 <div class="container">
     <h4 style="margin-top:20px; margin-bottom: 30px;"><b>공동구매 참여 내역</b></h4>
     <div class="table-wrap">
  <table class="board all-open">
    <caption></caption>
    <colgroup>
      <col>
      <col style="width:15%;">
      <col span="3">
    </colgroup>
    <thead>
      <tr>
        <th scope="col">상품번호</th>
        <th scope="col">상품정보</th>
        <th scope="col">상품명</th>
        <th scope="col">수량</th>
        <th scope="col">가격</th>
        <th scope="col">옵션</th>
        <th scope="col">참여일자</th>
        <th scope="col">채팅방 링크</th>
      </tr>
    </thead>
    <tbody>
      <tr>

          {% for product in products %}
          {% for join in join_objects %}
          {% if join.product_code.product_code == product.product_code %}
          {% for join_detail in join_detail_objects %}
          {% if join.join_code == join_detail.join_code.join_code %}
          {% for designated in designated_object %}
          {% if designated.product_code.product_code == product.product_code %}
          {% if user == join.username %}

        <td class="num">{{join.join_code}}</td>
        <td class="image"><a href="{{product.get_absolute_url}}"><img style="width: 90px" height= 90px" src="{{product.image.url}}" alt="상품 이미지"></a></td>
        <td class="subject2">{{join.product_code}}<a href="#" class="ellipsis"> </a><a href="#" title="{{product.name}}"></a>  </td>
        <td class="hit">{{join_detail.quantity}}개</td>
        <td class="date">{{join_detail.price}}원</td>
        <td class="option">{{join_detail.value_code}}</td>
        <td class="name">{{join.part_date|date:"Y-m-d"}}</td>
        <td class="link2"><a href="{{ product.kakao_link }}">링크열기</a></td>
      </tr>

      {% endif %}
  {% endif %}
                {% endfor %}
      {% endif %}
          {% endfor %}
       {% endif %}
    {% endfor %}
        {% endfor %}

    </tbody>
  </table>
</div>
 </div>

{% endblock %}

mypage/templates/mypage/mypage_list.html
{% extends 'base.html' %}
{% block title %} 마이페이지 {% endblock %}
{% block content %}

<header>
<meta name="viewport" content="width=device-width, initial-scale=1">
</header>

<style>

html, body{
    width:100%;
    overflow-x:hidden;
}

vr {
    display: block;
    width: 2px;
    height: 550px;
    background-color: darkgrey;
    position: absolute;
    top: 330px;
    bottom: 0;
    left: 50%;
    opacity: 0.2;
}

.card-text {
    margin-left: 10px;
    margin-top: -10px;
}

.card {
    float: right;
    margin-bottom:20px;
    width: 25rem;
    width: 80%;
    margin-right: 40px;
}

.cardcontainer {
    position: relative;
    float: right;
    margin-right: 50px;
    width: 450px;
    margin-top: -500px;
}

.card-body {
    margin-bottom: 8px;
}

  @media screen and (max-width: 1025px) {
  .cardcontainer {
      clear: right;
      max-width: 370px;
      margin-right: 90px;
      margin-bottom: 20px;
  }
}

@media screen and (max-width: 600px) {
vr {
    display: none;
    }
}

@media screen and (max-width:600px) {
.mypage {
    margin-top: -70px;
    transform: translate(-17%);
    }
}

@media screen and (max-width:600px) {
.content2 {
    margin-top: -50px;
    transform: translate(-18%, 10%);
    }
}

  @media screen and (max-width: 1025px) {
  .content2 input {
      max-width: 295px;

  }
}

@media screen and (max-width:600px) {
.cardcontainer {
    margin-top: 30px;
    transform: translate(28%);
    }
}


@media screen and (max-width: 600px) {
    .modify {
        margin-top: 55px;
         transform: translate(-18%);
    }
}

@media screen and (max-width: 600px) {
    .footer {
    display:none;
    }
}
</style>

<body>
 <div class="container">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
   <form method="POST">
     {% csrf_token %}

    <div class="mypage" style="margin-left: 70px;">
        <h4 style="margin-top:70px; color: #6E6E6E"><b><p style="color: #637B46; display: inline; clear:none;">{{ user.username }}</p>님의 마이페이지</b></h4>
        <h5 style="margin-top:40px; margin-bottom: 30px; color: #848484; clear: none;">내 정보</h5>
    </div>

    <div class="content2">
        <div id="username" style="margin-left: 85px; margin-top: 20px;">
             <strong style="color: #848484; margin-bottom: 10px;">이름</strong><br>
             <input style="color:#585858; margin-top: 8px; width: 350px; height: 45px; padding: 10px;" type="text" value="{{ user.name }}" name="name">
        </div>

         <div class="form-group" id="userid" style="margin-left: 85px; margin-top: 20px;">
             <strong style="color: #848484; margin-bottom: 10px;">아이디</strong><br>
             <input style="color:#585858; margin-top: 8px; width: 350px; height: 45px; padding: 10px;" type="text" value="{{ user.username }}" name="username" disabled>
        </div>

         <div id="userphone" style="margin-left: 85px; margin-top: 20px;">
             <strong style="color: #848484; margin-bottom: 10px;">전화번호</strong><br>
             <input style="color:#585858; margin-top: 8px; width: 350px; height: 45px; padding: 10px;" type="text" value="{{ user.phone }}" name="userphone">
         </div>

         <div id="useremail" style="margin-left: 85px; margin-top: 20px; margin-bottom: 30px;">
             <strong style="color: #848484; margin-bottom: 10px;">이메일</strong><br>
             <input style="color:#585858; margin-top: 8px; width: 350px; height: 45px; padding: 10px;" type="text" value="{{ user.email }}" name="useremail">
         </div>
    </div>

       <div class="modify">
        <span style="margin-left: 85px;"><a href="{% url 'zeronine:mypage_pwchange' %}" style="text-decoration: none;"><b style="color: grey;">비밀번호 변경하기</b></a></span>&nbsp;&nbsp;&nbsp;<span>|</span>&nbsp;&nbsp;
        <span><a href="{% url 'zeronine:profile_delete' %}" style="text-decoration: none;"><b style="color: grey; text-decoration: none;">탈퇴하기</b></a></span><br>

           <a onclick="alert('회원 정보가 변경되었습니다.');" style="cursor:pointer;">
              <button type="submit" action="{% url 'zeronine:mypage_list' %}" style="margin-top:20px; margin-left:85px; background: #637B46; border-color: #637B46; border-radius: 0px; text-align: center; width: 170px; height:55px;" class="btn btn-primary"><b>변경 사항 수정하기</b></button>
           </a>
    <vr></vr>
       </div>

       <div class="cardcontainer">
            <a href="{% url 'zeronine:mypage_joinlist' %}" style="color: black"><div class="card">
              <div class="card-body">
                  <h5 class="card-title"><img src="/static/img/cart.png" style="margin-bottom:2px; width:15%;"><b style="color: #424242;">참여 상품</b></h5>
                  <p class="card-text">&nbsp;내가 참여한 공동구매 상품 보러가기</p>
              </div>
            </div>
            </a>

              <a href="{% url 'zeronine:mypage_uploadlist' %}" style="color: black"><div class="card" style="width: 80%; margin-right: 40px;">
              <div class="card-body">
                  <h5 class="card-title" style="margin-top: 10px;"><img src="/static/img/check.png" style="margin-bottom:2px; width:7%; margin-left: 14px; margin-right: 12px;"><b style="color: #424242;">주최한 상품</b></h5>
                <p class="card-text" style="margin-top: 15px;">&nbsp;내가 주최한 공동구매 상품 보러가기</p>
              </div>
            </div>

            <a href="{% url 'zeronine:mypage_zzimlist' %}" style="color: black"><div class="card" style="width: 80%; margin-right: 40px;">
              <div class="card-body" style="margin-bottom: 8px;">
                  <h5 class="card-title"><img src="/static/img/zzim.png" style="margin-bottom:2px; width:15%; margin-left: 3px;"><b style="color: #424242;">찜 목록</b></h5>
                <p class="card-text">&nbsp;내가 찜한 상품 보러가기</p>
              </div>
            </div>
            </a>
            </a>
       </div>

</form>
</div>
</body>
{% endblock %}

mypage/templates/mypage/mypage_zzimlist.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>

.paragraph--type--card-narrow-row {
 display: flex;
 align-items: flex-start;
 justify-content: left;
 flex-flow: row wrap;
 margin-left: 50px;
 margin-top: 23px;
}

.myzzim {
   width: 200px; margin-top:50px; margin-bottom:20px; margin-left:69px; font-size: 23px;
}

 .card-narrow {
  transition: all .6s;
  width: 300px;
  height: 370px;
  border: 1px solid #ccc;
  margin: 20px;
  display: flex;
  flex-direction: column;
  }

.card-narrow-image {height: 280px;}

.card-narrow h3 {
    margin: 0;
    padding: 10px 0;
    text-align: center;
    line-height: 1.2;
    font-family: "Raleway",Arial,Helvetica,sans-serif;
    width: 100%;
    display: inline-block;
    vertical-align: middle;
    cursor: pointer;
    background-color: #eee;
}

.card-narrow p {
  padding: 0 10px;
  font-family: Arial,Helvetica,sans-serif;
  margin-bottom: 0;
}

.card-narrow-content {
  flex: 1 1 180px;

}
.card-narrow {
  background: #fff;
  border-radius: 2px;
  display: inline-block;
  box-shadow: 0 1px 2px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
  position: relative;

}

.card-narrow:hover {
  transform: translateY(-0.5rem) scale(1.0125);
  box-shadow: 0 0.5em 2.8rem -1rem rgba(0,0,0,0.5);
  transition-duration: 0.8s;
}

  @media screen and (max-width: 1025px) {
  .paragraph--type--card-narrow-row {
      margin-top: -15px;
      margin-left: 3px;
  }
}

  @media screen and (max-width: 1025px) {
  .myzzim {
      margin-top: 5px;
      margin-left: 23px;
  }
}

</style>

<link rel="stylesheet" href="{% static 'style.css' %}">

 <div class="container" style="margin-bottom: 20px;">

<h3 class="myzzim"><b>내가 찜한 상품</b></h3>

<div class="paragraph--type--card-narrow-row">

       {% for zzim in zzim %}
               {% if user == zzim.username %}
               {% for product in products %}
               {% if product.product_code == zzim.product_code.product_code %}


   <div class="card-narrow">
           <div class="card-narrow-image"><a href="{{product.get_absolute_url}}"><img style="margin-top:20px; width: 250px; height: 270px; margin-left:25px;" src="{{product.image.url}}" alt="상품 이미지"></a></div>
                <a onclick="return confirm('정말 삭제하시겠습니까?');">
                <form method="POST" action ="{% url 'zeronine:zzim_delete' pk=zzim.zzim_code%}">
                    {% csrf_token %}
                       <div class="form-group" style="outline:none;">
                          <button type="submit" class="btn btn-link" style="outline: none; background:none; border:none; margin-top: -510px;"><img src="/static/img/zzim2.png" style="outline:none; width:80px; margin-top: 10px;"></button>
                       </div>
                 </form>
          <div class="card-narrow-content" style="margin-top:-20px; justify-content: center; text-align: center"> <b style="font-size: 17px;">{{ zzim.product_code }}</b>
              {% endif %}
              {% endfor %}
                   <p style="margin-top: 5px;">
         {% for designated in designated_object %}
            {% if designated.product_code.product_code == zzim.product_code.product_code %}
            {{designated.price}}원
    </p>
    {% endif %}
    {% endfor %}
    </div>
    </a>
</div>
 {% endif %}
 {% endfor %}
</div>
 </div>
{% endblock %}

mypage/templates/mypage/profile_delete.html
{% extends 'base.html' %}

{% block content %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
@media screen and (min-width: 601px) {
  div.container {

  }
}

@media screen and (max-width: 600px) {
  div.container {

        font-size: 15px;
  }
}


</style>
<div class="container">
    <div style="margin-top: 4rem !important;">
        <div class="col-12">
            <div class="row justify-content-center" style="margin-top:20px; margin-bottom: 50px;">
                <div class="card" style="width: 500px;">
                    <div class="card-body">
                        <div class="h4">
                            <h4 style="margin-top:12px; margin-bottom: 25px"><b><p style="color:black; display: inline; clear:none;"><img src="/static/img/message.png" alt="message" style=" margin-bottom:5px; width:4.5%;">&nbsp;회원탈퇴</b></h4>
                        </div>
          <hr>
    <form method="POST" novalidate>
        {% csrf_token %}
        <p style="line-height: 1.6em;"><strong>{{ user.username }}</strong> 회원님의 계정이 삭제됩니다.<br>탈퇴 시, 개인정보 및 이용 정보가 삭제되며 복구할 수 없습니다. <br>비밀번호를 입력하신 후, 하단의 유의사항 동의에 체크하세요.</p>
        <div>
            <label name="label_password"> {{ password_form.password.label }}</label>
            {{ password_form.password }}
            {% if password_form.password.errors %}
            <script type="text/javascript">
                document.getElementsByName('password')[0].setAttribute('class', 'form-control is-invalid')
            </script>
            {% for error in password_form.password.errors %}
            <div class="invalid-feedback">
                {{ error }}
            </div>
            {% endfor %}
            {% endif %}
            <br>
            <h7>
                본인인증을 위해 비밀번호를 입력해주세요.
            </h7>
        </div>
    <br>
        <label>
            <input type="checkbox" name="ck" onClick="checkDisable(this.form)">
            <span>유의사항 동의</span>
        </label>
            <a onclick="return confirm('회원정보는 되돌릴 수 없습니다. 탈퇴를 진행하시겠습니까?');">
        <button type="submit" name="bt" disabled="true" style="float: right; width: 100px; height: 40px;  border-color: white";  class="btn btn-sm"><b>탈퇴하기</b></button></a>
    </form>

    <script type="text/javascript">
        function checkDisable(form) {
            if (form.ck.checked == true) {
                form.bt.disabled = false;
            } else {
                form.bt.disabled = true;
            }
        }
    </script>
          <br>

      </div>
    </div>
  </div>
</div>
</div>
</div>
{% endblock %}